Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -14,6 +14,7 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Deploy to Docker Compose
+        id: docker_deploy_step
         uses: appleboy/ssh-action@v0.1.8
         with:
           host: ${{ secrets.SERVER_HOST }}
@@ -22,13 +23,27 @@ jobs:
           timeout: 60s  
           command_timeout: 600s
           script: |
-              cd microservice-based-grade-management &&
-              git pull origin main &&
-              docker-compose pull &&
-              docker-compose down &&
-              docker-compose build &&
-              docker-compose up -d &&
-              docker system prune -a --force
+            set -e 
+            cd microservice-based-grade-management &&
+            git pull origin main &&
+            docker-compose pull &&
+            docker-compose down &&
+            docker-compose build &&
+            docker-compose up -d &&
+            docker system prune -a --force
+
+      - name: Handle Docker Deploy Failure
+        if: failure()  # Führt diesen Schritt nur aus, wenn der vorherige Schritt fehlschlägt
+        run: |
+          echo "Docker Compose Deployment has failed."
+    
+      
+      - name: Upload Docker Deploy Logs
+        if: failure()
+        uses: actions/upload-artifact@v3
+        with:
+          name: docker-deploy-logs
+          path: /pfad/zu/deinen/logs  # Passe den Pfad zu den tatsächlichen Logs an
 
   k3s-deploy:
     name: k3s Deployment
@@ -43,6 +58,7 @@ jobs:
         run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
 
       - name: Deploy to k3s
+        id: k3s_deploy_step
         uses: appleboy/ssh-action@v0.1.8
         with:
           host: ${{ secrets.SERVER_HOST }}
@@ -51,6 +67,7 @@ jobs:
           timeout: 60s  
           command_timeout: 600s
           script: |
+            set -e
             cd microservice-based-grade-management &&
             echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kubeconfig &&
             export KUBECONFIG=/etc/rancher/k3s/k3s.yaml &&
@@ -61,3 +78,9 @@ jobs:
             sleep 10 &&
             kubectl apply -f ./k8s/prometheus-service.yml --validate=false &&
             kubectl apply -f ./k8s/ --validate=false
+
+      - name: Handle k3s Deploy Failure
+        if: failure()
+        run: |
+          echo "k3s Deployment ist fehlgeschlagen. Sammle Logs und sende Benachrichtigung..."
+          # Hier ebenfalls Platzhalter für Log-Sammlung oder Benachrichtigung
